ACAO_ESPERAR = 0
ACAO_ESQUIVA = 1
ACAO_BLOQUEIO = 2
ACAO_ATAQUE_LEVE = 3
ACAO_ATAQUE_MEDIO = 4
ACAO_ATAQUE_PESADO = 5

# Alias legados
ACAO_DESTREZA = ACAO_ESQUIVA
ACAO_DEFENDER = ACAO_BLOQUEIO

ACOES_IA = [
  ACAO_ESPERAR,
  ACAO_ESQUIVA,
  ACAO_BLOQUEIO,
  ACAO_ATAQUE_LEVE,
  ACAO_ATAQUE_MEDIO,
  ACAO_ATAQUE_PESADO,
]

NOMES_ACAO = {
  ACAO_ESPERAR: "esperar",
  ACAO_ESQUIVA: "esquiva",
  ACAO_BLOQUEIO: "bloqueio",
  ACAO_ATAQUE_LEVE: "ataque_leve",
  ACAO_ATAQUE_MEDIO: "ataque_medio",
  ACAO_ATAQUE_PESADO: "ataque_pesado",
}


def nome_acao(acao):
  return NOMES_ACAO.get(int(acao), f"acao_{acao}")
