ACAO_NADA = 0
ACAO_DESTREZA = 1
ACAO_COMBO_SEGURO = 2
ACAO_BLOQUEIO = 3
ACAO_DEFENSIVO = 4
ACAO_ESPECIAL = 5

ACOES_IA = [
  ACAO_NADA,
  ACAO_DESTREZA,
  ACAO_COMBO_SEGURO,
  ACAO_BLOQUEIO,
  ACAO_ESPECIAL,
]
